apiVersion: v1
kind: Service
metadata:
  name: simpliroute-engine-service
spec:
  selector:
    app: simpliroute-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
